### PR TITLE
Extracting sync

### PR DESCRIPTION
**Pull request by wtrocki**
Extract sync related elements from SDK.

### CODE REVIEW

**Comment by matzew** [comment]
I have no clue on this

**Comment by wtrocki** [comment]
@matzew - Assigned you by mistake. Sorry

**Comment by danielpassos** [comment]
@wtrocki any reason why source files are in FH folder instead of in fh-ios-sdk?

**Comment by wtrocki** [comment]
@danielpassos That's problem. I'm going to rename everything to sync-ios. I just wanted to post extracted version in order to get that over the aerogear repository and leave fh-ios-sdk to be maintained only for 4.x versions.

**Comment by danielpassos** [comment]
@wtrocki I'm getting 2 erros:

FHSyncClient.m:256:21: No visible @interface for 'NetworkHandler' declares the selector 'performActRequest:WithArgs:AndSuccess:AndFailure:'

FHSyncClient.m:268:21: No visible @interface for 'NetworkHandler' declares the selector 'performActRequest:WithArgs:AndSuccess:AndFailure:'

Should we fix it before move on?

**Comment by danielpassos** [comment]
@wtrocki I've removed all push related in https://github.com/feedhenry/fh-sync-ios/pull/2. Going to do the same for the other features not used in sync :relaxed:

**Comment by wtrocki** [comment]
Work on hold as its unclear how much we can reuse from this sdk.

**Comment by danielpassos** [comment]
Is this still valid?

**Comment by wtrocki** [comment]
Work is valid in terms of improving Sync for Feedhenry Community (4.x), but it is not clear if this is going to be reused by AeroGear community. Closing as this still required some improvements. PR was linked and code could be reused in the future (but I think that we will probably write swift version instead)

**Pull request closed without merging**
